package entity_dto

type ENUM_ENTITY_TYPE string

const (
	ENTITY_USER        ENUM_ENTITY_TYPE = "USER"
	ENTITY_USER_OFFICE ENUM_ENTITY_TYPE = "USER_OFFICE"
	ENTITY_MESSAGE     ENUM_ENTITY_TYPE = "MESSAGE"
	ENTITY_CHAT        ENUM_ENTITY_TYPE = "CHAT"
	ENTITY_OFFICE      ENUM_ENTITY_TYPE = "OFFICE"
	ENTITY_HUB         ENUM_ENTITY_TYPE = "HUB"
)

var ENTITY_MAP = map[string]ENUM_ENTITY_TYPE{
	"USER":        ENTITY_USER,
	"USER_OFFICE": ENTITY_USER_OFFICE,
	"MESSAGE":     ENTITY_MESSAGE,
	"CHAT":        ENTITY_CHAT,
	"OFFICE":      ENTITY_OFFICE,
	"HUB":         ENTITY_HUB,
}
